### ISSUE TITLE
Add a hearth

### ISSUE THREAD

**Issue by Laurent-Werey** [nilCux/architecture-logicielle#21]
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes
![image](https://user-images.githubusercontent.com/12174047/216581709-e0dcc7b0-ced9-4518-8725-6406280dab68.png)

**Comment by nilCux** [comment]
Approuvé par M. Werey, on a décidé de faire une flèche à la place de Heart.
