### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by Laurent-Werey** [nilCux/architecture-logicielle#24]
Add a color picker, could be done with : 
- modal : https://ng-bootstrap.github.io/#/components/modal/examples
- collapse : https://ng-bootstrap.github.io/#/components/collapse/examples

**Comment by nilCux** [comment]
**Contexte**: 
La valeur de *ColorPaletteComponent.color* est appliqué à *PainterService.propertiesService.color* chaque fois quand le boutton de souris est laché(onMousdUp) dans la fênetre entière:
````Typescript
@HostListener('window:mouseup', ['$event'])
  onMouseUp(evt: MouseEvent) {
    this.mousedown = false;
    this.shapeManager.setColor(this.color);
  }
````

**Soucis:**
La valeur initiale de *ColorPaletteComponent.color* est *undefined*. Malgré que la valeur de *PainterService.propertiesService.color* est bien initialisé, sa valeur sera effacé par  la valeur initiale de *ColorPaletteComponent.color* qui est *undefined*.

**Conséquence:**
La couleur par défault n'est pas correcte. Pour les objet dessinné utilisant la couleur par défaut, leurs couleur change parfois.

**Fix proposé**:
Initialiser la valeur de *ColorPaletteComponent.color* dans son constructeur. Puis, dans sa méthode draw(), on utilises cette valeur à construire ll palette de couleur. 

```Typescript
constructor(private shapeManager: PainterService) { this.color = 'rgba(0,19,255,1)';}

draw() {
    const selectColorHeight = 10;

    this.ctx.fillStyle = this.hue || this.color;    
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    ...
}
```
