### ISSUE TITLE
Save and load button

### ISSUE THREAD

**Issue by Laurent-Werey** [nilCux/architecture-logicielle#26]
Interface
Add to the navbar a save and load button

Save : 
add a Save button that saves in a file the shape array.
We could just display the json in the first time ...

Load : 
Load a file and parse it to the shape array.
We could just have a text input for the json in the first time...

**Comment by Laurent-Werey** [comment]
also see : https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations
saving the hole canvas could be simpler .... but could cause problems, like saving ghosts or idk

**Comment by nilCux** [comment]
Upload fixed.
